package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"strings"
	"time"

	"crispypod.com/crispypod-backend/db"
	"crispypod.com/crispypod-backend/dbModels"
	eventhandler "crispypod.com/crispypod-backend/eventHandler"
	"crispypod.com/crispypod-backend/graph/model"
	"crispypod.com/crispypod-backend/helpers"
	"github.com/google/uuid"
	"github.com/gookit/event"
)

// CreateEpisode is the resolver for the createEpisode field.
func (r *mutationResolver) CreateEpisode(ctx context.Context, input *model.NewEpisode) (*model.Episode, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var jwtDbUser dbModels.DbUser
	if err := db.DB.Where(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
		return nil, errors.New("user not found")
	}

	var desc, title string
	desc, _ = url.QueryUnescape(input.Description)
	title, _ = url.QueryUnescape(input.Title)

	newEpisode := dbModels.Episode{
		ID:            uuid.New(),
		Title:         title,
		Description:   desc,
		EpisodeStatus: dbModels.EpisodeStatus_Draft,
		UserID:        jwtDbUser.ID,
		CreateTime:    time.Now(),
	}
	newEpisode.GenerateNamedLink()
	// check if generated named link was existed
	foundExistedEpisode := true
	for foundExistedEpisode {
		var nameLinkEp dbModels.Episode
		if err := db.DB.First(&nameLinkEp, "named_link = ?", newEpisode.NamedLink).Error; err != nil {
			break
		}
		newEpisode.NamedLink = fmt.Sprintf("%s-", newEpisode.NamedLink)
	}

	if input.AudioFileName != nil {
		newEpisode.AudioFileName.String = *input.AudioFileName
	}

	if input.AudioFileUploadName != nil {
		newEpisode.AudioFileUploadName.String = *input.AudioFileUploadName
	}

	if input.AudioFileDuration != nil {
		newEpisode.AudioFileDuration.Int64 = int64(*input.AudioFileDuration)
	}

	if input.ThumbnailFileName != nil {
		newEpisode.ThumbnailFileName.String = *input.ThumbnailFileName
	}

	if input.ThumbnailFileUploadName != nil {
		newEpisode.ThumbnailUploadName.String = *input.ThumbnailFileUploadName
	}

	db.DB.Create(newEpisode)

	return newEpisode.ToGQLEpisode(), nil
}

// ModifyEpisode is the resolver for the modifyEpisode field.
func (r *mutationResolver) ModifyEpisode(ctx context.Context, id string, input *model.ModifyEpisodeInput) (*model.Episode, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var jwtDbUser dbModels.DbUser
	if err := db.DB.Model(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
		return nil, errors.New("user not found")
	}

	var dbEpisode dbModels.Episode
	if err := db.DB.Where(dbModels.Episode{ID: uuid.Must(uuid.Parse(id))}).Find(&dbEpisode).Error; err != nil {
		return nil, errors.New("episode not found")
	}

	if input.Title != nil {
		title, _ := url.QueryUnescape(*input.Title)
		dbEpisode.Title = title
		dbEpisode.GenerateNamedLink()
		// check if generated named link was existed
		foundExistedEpisode := true
		for foundExistedEpisode {
			var existedEpisode dbModels.Episode
			if err := db.DB.First(&existedEpisode, "named_link = ? AND id <> ?", dbEpisode.NamedLink, dbEpisode.ID.String()).Error; err != nil {
				break
			}
			dbEpisode.NamedLink = fmt.Sprintf("%s-", dbEpisode.NamedLink)
		}

	}

	if input.Description != nil {
		description, _ := url.QueryUnescape(*input.Description)
		dbEpisode.Description = description
	}
	originStatus := dbEpisode.EpisodeStatus

	if input.EpisodeStatus != nil {
		dbEpisode.EpisodeStatus = dbModels.EpisodeStatusType(*input.EpisodeStatus)
	}

	if input.AudioFileName != nil {
		dbEpisode.AudioFileName = sql.NullString{String: *input.AudioFileName, Valid: true}
	}

	if input.AudioFileUploadName != nil {
		dbEpisode.AudioFileUploadName = sql.NullString{String: *input.AudioFileUploadName, Valid: true}
	}

	if input.AudioFileDuration != nil {
		dbEpisode.AudioFileDuration = sql.NullInt64{Int64: int64(*input.AudioFileDuration), Valid: true}
	}

	if input.ThumbnailFileName != nil {
		dbEpisode.ThumbnailFileName = sql.NullString{String: *input.ThumbnailFileName, Valid: true}
	}

	if input.ThumbnailFileUploadName != nil {
		dbEpisode.ThumbnailUploadName = sql.NullString{String: *input.ThumbnailFileUploadName, Valid: true}
	}

	db.DB.Save(dbEpisode)

	if originStatus != dbModels.EpisodeStatusType(*input.EpisodeStatus) {
		event.MustFire(string(eventhandler.EventType_EpisodeVisibilityChanged), event.M{"episode": dbEpisode})
	}

	return dbEpisode.ToGQLEpisode(), nil
}

// ModifySiteConfig is the resolver for the modifySiteConfig field.
func (r *mutationResolver) ModifySiteConfig(ctx context.Context, input *model.SiteConfigInput) (*model.SiteConfig, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var siteConfig dbModels.SiteConfig
	if err := db.DB.First(&siteConfig).Error; err != nil {
		return nil, errors.New("site config not found")
	}

	if input.SiteDescription != nil {
		siteConfig.SiteDescription = *input.SiteDescription
	}

	if input.SiteName != nil {
		siteConfig.SiteName = *input.SiteName
	}

	if input.SiteURL != nil {
		siteConfig.SiteUrl = *input.SiteURL
	}

	if input.SetupComplete != nil && *input.SetupComplete {
		siteConfig.SetupComplete = true
	}

	if input.DefaultThumbnail != nil {
		siteConfig.DefaultThumbnail = sql.NullString{
			String: *input.DefaultThumbnail,
			Valid:  true,
		}
	}

	if input.SiteIconFile != nil {
		siteConfig.SiteIconFile = sql.NullString{
			String: *input.SiteIconFile,
			Valid:  true,
		}
	}

	db.DB.Save(siteConfig)

	event.MustFire(string(eventhandler.EventType_SiteConfigChanged), event.M{"siteConfig": siteConfig})

	return siteConfig.ToGQLSiteConfig(len(userName) != 0), nil
}

// ModifyMe is the resolver for the modifyMe field.
func (r *mutationResolver) ModifyMe(ctx context.Context, input model.UserInput) (*model.User, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbJWTUser dbModels.DbUser
	if err := db.DB.Model(&dbModels.DbUser{UserName: userName}).Find(&dbJWTUser).Error; err != nil {
		return nil, errors.New(err.Error())
	}

	dbJWTUser.Email = input.Email
	dbJWTUser.UserName = input.UserName
	dbJWTUser.DisplayName = input.DisplayName

	if input.Password != nil {
		newPassword, _ := helpers.HashPassword(*input.Password)
		dbJWTUser.Password = newPassword
	}

	db.DB.Save(dbJWTUser)

	return dbJWTUser.ToGQLUser(), nil
}

// DeleteEpisode is the resolver for the deleteEpisode field.
func (r *mutationResolver) DeleteEpisode(ctx context.Context, id string) (*model.BooleanResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbEpisode dbModels.Episode
	if err := db.DB.Find(&dbEpisode, dbModels.Episode{ID: uuid.Must(uuid.Parse(id))}).Error; err != nil {
		return nil, errors.New("episode not found")
	}

	if err := db.DB.Delete(dbEpisode).Error; err != nil {
		return nil, errors.New("failed to delete episode")
	}

	return &model.BooleanResult{Result: true}, nil
}

// CreateHook is the resolver for the createHook field.
func (r *mutationResolver) CreateHook(ctx context.Context, input *model.HookInput) (*model.Hook, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// var jwtDbUser dbModels.DbUser
	// if err := db.DB.Where(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
	// 	return nil, errors.New("user not found")
	// }

	var name, weburl, method string
	name, _ = url.QueryUnescape(input.Name)
	weburl, _ = url.QueryUnescape(input.WebURL)
	_method, _ := url.QueryUnescape(input.Method)

	method = strings.ToUpper(_method)

	if !helpers.URLValidate(weburl) {
		return nil, errors.New("invalid WebURL, please include 'http://' or 'https://'")
	}

	if !helpers.MethodValidate(method) {
		return nil, errors.New("invalid Method, please provide correct http method")
	}

	newHook := dbModels.Hook{
		ID:         uuid.New(),
		Name:       name,
		WebURL:     weburl,
		Trigger:    dbModels.HookTriggerType(input.Trigger),
		Method:     method,
		CreateTime: time.Now(),
	}

	if input.Headers != nil {
		headers, _ := url.QueryUnescape(*input.Headers)
		if !helpers.JsonValidate(headers) {
			return nil, errors.New("invalid headers, please provide headers in valid json format")
		}
		newHook.Headers.String = headers
	}

	if input.AppendBody != nil {
		appendBody, _ := url.QueryUnescape(*input.AppendBody)
		if !helpers.JsonValidate(appendBody) {
			return nil, errors.New("invalid appendBody, please provide appendBody in valid json format")
		}
		newHook.AppendBody.String = appendBody
	}

	db.DB.Create(newHook)
	return newHook.ToGQLHook(), nil
}

// ModifyHook is the resolver for the modifyHook field.
func (r *mutationResolver) ModifyHook(ctx context.Context, input *model.HookInput, id string) (*model.Hook, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// var jwtDbUser dbModels.DbUser
	// if err := db.DB.Where(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
	// 	return nil, errors.New("user not found")
	// }

	var dbHook dbModels.Hook
	hookId, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid hook id")
	}
	if err := db.DB.Where(dbModels.Hook{ID: hookId}).Find(&dbHook).Error; err != nil {
		return nil, errors.New("hook not found")
	}

	dbHook.Name = input.Name
	dbHook.Trigger = dbModels.HookTriggerType(input.Trigger)
	dbHook.WebURL = input.WebURL
	dbHook.Method = input.Method
	dbHook.ModifyTime = time.Now()

	if input.Headers != nil {
		headers, _ := url.QueryUnescape(*input.Headers)
		if !helpers.JsonValidate(headers) {
			return nil, errors.New("invalid headers, please provide headers in valid json format")
		}
		dbHook.Headers = sql.NullString{String: headers, Valid: true}
	}

	if input.AppendBody != nil {
		appendBody, _ := url.QueryUnescape(*input.AppendBody)
		if !helpers.JsonValidate(appendBody) {
			return nil, errors.New("invalid appendBody, please provide appendBody in valid json format")
		}
		dbHook.AppendBody = sql.NullString{String: appendBody, Valid: true}
	}

	db.DB.Save(dbHook)
	return dbHook.ToGQLHook(), nil
}

// DeleteHook is the resolver for the deleteHook field.
func (r *mutationResolver) DeleteHook(ctx context.Context, id string) (*model.BooleanResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// var jwtDbUser dbModels.DbUser
	// if err := db.DB.Where(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
	// 	return nil, errors.New("user not found")
	// }

	var dbHook dbModels.Hook
	if err := db.DB.Find(&dbHook, dbModels.Hook{ID: uuid.Must(uuid.Parse(id))}).Error; err != nil {
		return nil, errors.New("hook not found")
	}

	if err := db.DB.Delete(dbHook).Error; err != nil {
		return nil, errors.New("failed to delete hook")
	}

	// TODO: delete hook log, maybe we can add to scheduled job
	return &model.BooleanResult{Result: true}, nil
}

// EpisodeList is the resolver for the episodeList field.
func (r *queryResolver) EpisodeList(ctx context.Context, pagination model.Pagination) (*model.EpisodeListResult, error) {
	var episodes []dbModels.Episode
	var rtEpisodes []*model.Episode
	var count int64
	if userName := helpers.JWTFromContext(ctx); len(userName) == 0 {
		err := db.DB.
			Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
			Order("create_time DESC").
			Find(&episodes, dbModels.Episode{EpisodeStatus: dbModels.EpisodeStatus_Published}).Error
		if err != nil {
			return nil, errors.New("episodes not found")
		}
		err = db.DB.Model(dbModels.Episode{}).Where(dbModels.Episode{EpisodeStatus: dbModels.EpisodeStatus_Published}).Count(&count).Error
		if err != nil {
			return nil, errors.New("episodes not found")
		}
	} else {
		if err := db.DB.Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
			Order("create_time DESC").
			Find(&episodes).Error; err != nil {
			return nil, errors.New("episodes not found")
		}
		if err := db.DB.Model(dbModels.Episode{}).Count(&count).Error; err != nil {
			return nil, errors.New("episodes not found")
		}
	}
	// Convert
	for _, e := range episodes {
		rtEpisodes = append(rtEpisodes, e.ToGQLEpisode())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))
	// return rtEpisodes, nil
	return &model.EpisodeListResult{
		TotalCount: int(count),
		Items:      rtEpisodes,
		PageInfo:   &pageInfo,
	}, nil
}

// Episode is the resolver for the episode field.
func (r *queryResolver) Episode(ctx context.Context, id *string, namedLink *string) (*model.Episode, error) {
	userName := helpers.JWTFromContext(ctx)
	var dbEpisode dbModels.Episode
	if id == nil && namedLink == nil {
		return nil, errors.New("invalid parameter")
	}

	if id != nil {
		epId, err := uuid.Parse(*id)
		if err != nil {
			return nil, errors.New("invalid episode id")
		}
		if err := db.DB.Find(&dbEpisode, dbModels.Episode{ID: uuid.Must(epId, err)}).Error; err != nil {
			return nil, errors.New("episode not found")
		}
	}
	if namedLink != nil {
		if err := db.DB.Find(&dbEpisode, dbModels.Episode{NamedLink: *namedLink}).Error; err != nil {
			return nil, errors.New("episode not found")
		}
	}

	if len(userName) == 0 && dbEpisode.EpisodeStatus == dbModels.EpisodeStatus_Draft {
		// check if episode status was draft, if so, we will not return it while user has not logged in
		return nil, errors.New("episode not accessable")
	}
	return dbEpisode.ToGQLEpisode(), nil
}

// UserList is the resolver for the userList field.
func (r *queryResolver) UserList(ctx context.Context, pagination model.Pagination) (*model.UserListResult, error) {
	var count int64
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbJWTUser dbModels.DbUser
	if err := db.DB.Find(&dbJWTUser, dbModels.DbUser{UserName: userName}).Count(&count).Error; err != nil {
		return nil, errors.New(err.Error())
	}
	if !dbJWTUser.IsAdmin {
		return nil, errors.New("user not to access this data")
	}

	var users []dbModels.DbUser
	if err := db.DB.Model(&dbModels.DbUser{}).Count(&count).Find(&users).Error; err != nil {
		return nil, errors.New(err.Error())
	}

	var rtUsers []*model.User
	for _, u := range users {
		rtUsers = append(rtUsers, u.ToGQLUser())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))
	return &model.UserListResult{
		TotalCount: int(count),
		Items:      rtUsers,
		PageInfo:   &pageInfo,
	}, nil
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, credential model.Credential) (*model.LoginData, error) {
	var user dbModels.DbUser
	if err := db.DB.Model(dbModels.DbUser{UserName: credential.UserName}).First(&user).Error; err != nil {
		return nil, errors.New("user with provided credentials not found")
	}
	if helpers.CheckPasswordHash(credential.Password, user.Password) {
		token, _ := helpers.GenerateJwt(user.UserName)
		return &model.LoginData{
			Token: token,
		}, nil
	}
	return nil, errors.New("user with provided credentials not found")
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbJWTUser dbModels.DbUser
	if err := db.DB.Model(&dbModels.DbUser{UserName: userName}).Find(&dbJWTUser).Error; err != nil {
		return nil, errors.New(err.Error())
	}

	return dbJWTUser.ToGQLUser(), nil
}

// SiteConfig is the resolver for the siteConfig field.
func (r *queryResolver) SiteConfig(ctx context.Context) (*model.SiteConfig, error) {
	var siteConfig dbModels.SiteConfig
	userName := helpers.JWTFromContext(ctx)
	if err := db.DB.First(&siteConfig).Error; err != nil {
		siteConfig = dbModels.SiteConfig{
			ID:              uuid.New(),
			SiteName:        "CrispyPod",
			SiteDescription: "Super awesome podcast!",
			SiteUrl:         "https://crispypod.com",
			SetupComplete:   false,
		}
		db.DB.Create(&siteConfig)
	}

	return siteConfig.ToGQLSiteConfig(len(userName) != 0), nil
}

// DashboardInfo is the resolver for the dashboardInfo field.
func (r *queryResolver) DashboardInfo(ctx context.Context) (*model.DashboardInfo, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var rtn = &model.DashboardInfo{}
	var count int64
	db.DB.Model(dbModels.Episode{}).Count(&count)
	rtn.EpisodeCount = int(count)
	return rtn, nil
}

// HookList is the resolver for the hookList field.
func (r *queryResolver) HookList(ctx context.Context, pagination model.Pagination) (*model.HookListResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// var jwtDbUser dbModels.DbUser
	// if err := db.DB.Model(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
	// 	return nil, errors.New("user not found")
	// }

	var hooks []dbModels.Hook
	var count int64
	err := db.DB.Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
		Order("create_time DESC").
		Find(&hooks).Error
	if err != nil {
		return nil, errors.New("hooks not found")
	}
	err = db.DB.Model(dbModels.Hook{}).Count(&count).Error
	if err != nil {
		return nil, errors.New("hooks not found")
	}

	var rtHooks []*model.Hook
	for _, h := range hooks {
		rtHooks = append(rtHooks, h.ToGQLHook())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))

	return &model.HookListResult{
		TotalCount: int(count),
		Items:      rtHooks,
		PageInfo:   &pageInfo,
	}, nil
}

// Hook is the resolver for the hook field.
func (r *queryResolver) Hook(ctx context.Context, id string) (*model.Hook, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// var jwtDbUser dbModels.DbUser
	// if err := db.DB.Model(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
	// 	return nil, errors.New("user not found")
	// }

	var dbHook dbModels.Hook
	hID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid hook id")
	}

	if err := db.DB.Find(&dbHook, dbModels.Hook{ID: uuid.Must(hID, err)}).Error; err != nil {
		return nil, errors.New("hook not found")
	}

	return dbHook.ToGQLHook(), nil
}

// HookLogList is the resolver for the hookLogList field.
func (r *queryResolver) HookLogList(ctx context.Context, pagination model.Pagination, hookID string) (*model.HookLogListResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// var jwtDbUser dbModels.DbUser
	// if err := db.DB.Model(dbModels.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
	// 	return nil, errors.New("user not found")
	// }

	var logs []dbModels.HookLog
	var count int64
	err := db.DB.Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
		Order("create_time DESC").
		Find(&logs).Error

	if err != nil {
		return nil, errors.New("logs not found")
	}

	err = db.DB.Model(dbModels.HookLog{}).Count(&count).Error
	if err != nil {
		return nil, errors.New("logs not found")
	}

	var rtLogs []*model.HookLog
	for _, l := range logs {
		rtLogs = append(rtLogs, l.ToGQLHookLog())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))

	return &model.HookLogListResult{
		TotalCount: int(count),
		Items:      rtLogs,
		PageInfo:   &pageInfo,
	}, nil
}

// HookLog is the resolver for the hookLog field.
func (r *queryResolver) HookLog(ctx context.Context, id string) (*model.HookLog, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbHookLog dbModels.HookLog
	hlID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid hookLog id")
	}

	if err := db.DB.Find(&dbHookLog, dbModels.HookLog{ID: hlID}).Error; err != nil {
		return nil, errors.New("hookLog not found")
	}

	return dbHookLog.ToGQLHookLog(), nil
	// panic(fmt.Errorf("not implemented: HookLog - hookLog"))
}

// DeployLogList is the resolver for the deployLogList field.
func (r *queryResolver) DeployLogList(ctx context.Context, pagination model.Pagination) (*model.DeployLogListResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var logs []dbModels.DeployLog
	var count int64

	err := db.DB.Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
		Order("create_time DESC").
		Find(&logs).Error

	if err != nil {
		return nil, errors.New("logs not found")
	}

	err = db.DB.Model(dbModels.DeployLog{}).Count(&count).Error
	if err != nil {
		return nil, errors.New("logs not found")
	}

	var rtLogs []*model.DeployLog
	for _, l := range logs {
		rtLogs = append(rtLogs, l.ToGQLDeployLog())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))

	return &model.DeployLogListResult{
		TotalCount: int(count),
		Items:      rtLogs,
		PageInfo:   &pageInfo,
	}, nil
}

// DeployLog is the resolver for the deployLog field.
func (r *queryResolver) DeployLog(ctx context.Context, id string) (*model.DeployLog, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbDeployLog dbModels.DeployLog
	dlID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid deploy log id")
	}
	if err := db.DB.Find(&dbDeployLog, dbModels.DeployLog{ID: uuid.Must(dlID, err)}).Error; err != nil {
		return nil, errors.New("deploy log not found")
	}
	return dbDeployLog.ToGQLDeployLog(), nil
}

// TriggerHook is the resolver for the triggerHook field.
func (r *queryResolver) TriggerHook(ctx context.Context, id string) (*model.BooleanResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// TODO
	var dbHook dbModels.Hook
	hID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid hook id")
	}

	if err := db.DB.Find(&dbHook, dbModels.Hook{ID: hID}).Error; err != nil {
		return nil, errors.New("hook not found")
	}

	switch dbHook.Trigger {
	case dbModels.HookTriggerType_EpisodeVisibilityChanged:
		var episode dbModels.Episode
		if err := db.DB.First(&episode).Error; err != nil {
			episode = dbModels.Episode{
				ID:    uuid.New(),
				Title: "Test Episode",
			}
		}
		go eventhandler.TriggerHook(dbHook, episode)
	case dbModels.HookTriggerType_SiteConfigChanged:
		var siteConfig dbModels.SiteConfig
		if err := db.DB.First(&siteConfig).Error; err != nil {
			siteConfig = dbModels.SiteConfig{
				ID:              uuid.New(),
				SiteName:        "CrispyPod",
				SiteDescription: "Super awesome podcast!",
				SiteUrl:         "https://crispypod.com",
				SetupComplete:   false,
			}
			db.DB.Create(&siteConfig)
		}
		go eventhandler.TriggerHook(dbHook, siteConfig)
	}

	return &model.BooleanResult{
		Result: true,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
