package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"strings"
	"time"

	"crispypod.com/crispypod-backend/db"
	"crispypod.com/crispypod-backend/graph/model"
	"crispypod.com/crispypod-backend/helpers"
	"crispypod.com/crispypod-backend/models"
	"crispypod.com/crispypod-backend/rssfeed"
	"github.com/google/uuid"
)

// CreateEpisode is the resolver for the createEpisode field.
func (r *mutationResolver) CreateEpisode(ctx context.Context, input *model.NewEpisode) (*model.Episode, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var jwtDbUser models.DbUser
	if err := db.DB.Where(models.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
		return nil, errors.New("user not found")
	}

	var desc, title string
	desc, _ = url.QueryUnescape(input.Description)
	title, _ = url.QueryUnescape(input.Title)

	newEpisode := models.Episode{
		ID:            uuid.New(),
		Title:         title,
		Description:   desc,
		EpisodeStatus: models.EpisodeStatus_Draft,
		UserID:        jwtDbUser.ID,
		CreateTime:    time.Now(),
	}

	if input.AudioFileName != nil {
		newEpisode.AudioFileName.String = *input.AudioFileName
	}

	if input.AudioFileUploadName != nil {
		newEpisode.AudioFileUploadName.String = *input.AudioFileUploadName
	}

	if input.AudioFileDuration != nil {
		newEpisode.AudioFileDuration.Int64 = int64(*input.AudioFileDuration)
	}

	if input.ThumbnailFileName != nil {
		newEpisode.ThumbnailFileName.String = *input.ThumbnailFileName
	}

	if input.ThumbnailFileUploadName != nil {
		newEpisode.ThumbnailUploadName.String = *input.ThumbnailFileUploadName
	}

	db.DB.Create(newEpisode)
	go rssfeed.GenerateRSSFeed()

	return newEpisode.ToGQLEpisode(), nil
}

// ModifyEpisode is the resolver for the modifyEpisode field.
func (r *mutationResolver) ModifyEpisode(ctx context.Context, id string, input *model.ModifyEpisodeInput) (*model.Episode, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var jwtDbUser models.DbUser
	if err := db.DB.Model(models.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
		return nil, errors.New("user not found")
	}

	var dbEpisode models.Episode
	if err := db.DB.Where(models.Episode{ID: uuid.Must(uuid.Parse(id))}).Find(&dbEpisode).Error; err != nil {
		return nil, errors.New("episode not found")
	}

	if input.Title != nil {
		title, _ := url.QueryUnescape(*input.Title)
		dbEpisode.Title = title
	}

	if input.Description != nil {
		description, _ := url.QueryUnescape(*input.Description)
		dbEpisode.Description = description
	}

	if input.EpisodeStatus != nil {
		dbEpisode.EpisodeStatus = models.EpisodeStatusType(*input.EpisodeStatus)
	}

	if input.AudioFileName != nil {
		dbEpisode.AudioFileName = sql.NullString{String: *input.AudioFileName, Valid: true}
	}

	if input.AudioFileUploadName != nil {
		dbEpisode.AudioFileUploadName = sql.NullString{String: *input.AudioFileUploadName, Valid: true}
	}

	if input.AudioFileDuration != nil {
		dbEpisode.AudioFileDuration = sql.NullInt64{Int64: int64(*input.AudioFileDuration), Valid: true}
	}

	if input.ThumbnailFileName != nil {
		dbEpisode.ThumbnailFileName = sql.NullString{String: *input.ThumbnailFileName, Valid: true}
	}

	if input.ThumbnailFileUploadName != nil {
		dbEpisode.ThumbnailUploadName = sql.NullString{String: *input.ThumbnailFileUploadName, Valid: true}
	}

	db.DB.Save(dbEpisode)
	go rssfeed.GenerateRSSFeed()

	return dbEpisode.ToGQLEpisode(), nil
}

// ModifySiteConfig is the resolver for the modifySiteConfig field.
func (r *mutationResolver) ModifySiteConfig(ctx context.Context, input *model.SiteConfigInput) (*model.SiteConfig, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var siteConfig models.SiteConfig
	if err := db.DB.First(&siteConfig).Error; err != nil {
		return nil, errors.New("site config not found")
	}

	if input.SiteDescription != nil {
		siteConfig.SiteDescription = *input.SiteDescription
	}

	if input.SiteName != nil {
		siteConfig.SiteName = *input.SiteName
	}

	if input.SiteURL != nil {
		siteConfig.SiteUrl = *input.SiteURL
	}

	if input.SetupComplete != nil && *input.SetupComplete {
		siteConfig.SetupComplete = true
	}

	db.DB.Save(siteConfig)
	go rssfeed.GenerateRSSFeed()

	return siteConfig.ToGQLSiteConfig(len(userName) != 0), nil
}

// ModifyMe is the resolver for the modifyMe field.
func (r *mutationResolver) ModifyMe(ctx context.Context, input model.UserInput) (*model.User, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbJWTUser models.DbUser
	if err := db.DB.Model(&models.DbUser{UserName: userName}).Find(&dbJWTUser).Error; err != nil {
		return nil, errors.New(err.Error())
	}

	dbJWTUser.Email = input.Email
	dbJWTUser.UserName = input.UserName
	dbJWTUser.DisplayName = input.DisplayName

	if input.Password != nil {
		newPassword, _ := helpers.HashPassword(*input.Password)
		dbJWTUser.Password = newPassword
	}

	db.DB.Save(dbJWTUser)

	return dbJWTUser.ToGQLUser(), nil
}

// DeleteEpisode is the resolver for the deleteEpisode field.
func (r *mutationResolver) DeleteEpisode(ctx context.Context, id string) (*model.BooleanResult, error) {
	// panic(fmt.Errorf("not implemented: DeleteEpisode - deleteEpisode"))
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbEpisode models.Episode
	if err := db.DB.Find(&dbEpisode, models.Episode{ID: uuid.Must(uuid.Parse(id))}).Error; err != nil {
		return nil, errors.New("episode not found")
	}

	if err := db.DB.Delete(dbEpisode).Error; err != nil {
		return nil, errors.New("failed to delete episode")
	}

	return &model.BooleanResult{Result: true}, nil
}

// CreateHook is the resolver for the createHook field.
func (r *mutationResolver) CreateHook(ctx context.Context, input *model.HookInput) (*model.Hook, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var jwtDbUser models.DbUser
	if err := db.DB.Where(models.DbUser{UserName: userName}).Find(&jwtDbUser).Error; err != nil {
		return nil, errors.New("user not found")
	}

	var name, weburl, method string
	name, _ = url.QueryUnescape(input.Name)
	weburl, _ = url.QueryUnescape(input.WebURL)
	_method, _ := url.QueryUnescape(input.Method)

	method = strings.ToUpper(_method)

	if !helpers.URLValidate(weburl) {
		return nil, errors.New("invalid WebURL, please include 'http://' or 'https://'")
	}

	if !helpers.MethodValidate(method) {
		return nil, errors.New("invalid Method, please provide correct http method")
	}

	newHook := models.Hook{
		ID:      uuid.New(),
		Name:    name,
		WebURL:  weburl,
		Trigger: models.HookTriggerType(input.Trigger),
		Method:  method,
	}

	if input.Headers != nil {
		headers, _ := url.QueryUnescape(*input.Headers)
		if !helpers.JsonValidate(headers) {
			return nil, errors.New("invalid headers, please provide headers in valid json format")
		}
		newHook.Headers.String = headers
	}

	if input.AppendBody != nil {
		appendBody, _ := url.QueryUnescape(*input.AppendBody)
		if !helpers.JsonValidate(appendBody) {
			return nil, errors.New("invalid appendBody, please provide appendBody in valid json format")
		}
		newHook.AppendBody.String = appendBody
	}

	db.DB.Create(newHook)
	return newHook.ToGQLHook(), nil
}

// ModifyHook is the resolver for the modifyHook field.
func (r *mutationResolver) ModifyHook(ctx context.Context, input *model.HookInput, id string) (*model.Hook, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: ModifyHook - modifyHook"))
}

// DeleteHook is the resolver for the deleteHook field.
func (r *mutationResolver) DeleteHook(ctx context.Context, id string) (*model.BooleanResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: DeleteHook - deleteHook"))
}

// EpisodeList is the resolver for the episodeList field.
func (r *queryResolver) EpisodeList(ctx context.Context, pagination model.Pagination) (*model.EpisodeListResult, error) {
	var episodes []models.Episode
	var rtEpisodes []*model.Episode
	var count int64
	if userName := helpers.JWTFromContext(ctx); len(userName) == 0 {
		err := db.DB.
			Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
			Order("create_time DESC").
			Find(&episodes, models.Episode{EpisodeStatus: models.EpisodeStatus_Published}).Error
		if err != nil {
			return nil, errors.New("episodes not found")
		}
		err = db.DB.Model(models.Episode{}).Where(models.Episode{EpisodeStatus: models.EpisodeStatus_Published}).Count(&count).Error
		if err != nil {
			return nil, errors.New("episodes not found")
		}
	} else {
		if err := db.DB.Scopes(helpers.Paginate(pagination.PageIndex, pagination.PerPage)).
			Order("create_time DESC").
			Find(&episodes).Error; err != nil {
			return nil, errors.New("episodes not found")
		}
		if err := db.DB.Model(models.Episode{}).Count(&count).Error; err != nil {
			return nil, errors.New("episodes not found")
		}
	}
	// Convert
	for _, e := range episodes {
		rtEpisodes = append(rtEpisodes, e.ToGQLEpisode())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))
	// return rtEpisodes, nil
	return &model.EpisodeListResult{
		TotalCount: int(count),
		Items:      rtEpisodes,
		PageInfo:   &pageInfo,
	}, nil
}

// Episode is the resolver for the episode field.
func (r *queryResolver) Episode(ctx context.Context, id string) (*model.Episode, error) {
	userName := helpers.JWTFromContext(ctx)
	var dbEpisode models.Episode
	epId, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("invalid episode id")
	}
	if err := db.DB.Find(&dbEpisode, models.Episode{ID: uuid.Must(epId, err)}).Error; err != nil {
		return nil, errors.New("episode not found")
	}
	if len(userName) == 0 && dbEpisode.EpisodeStatus == models.EpisodeStatus_Draft {
		// check if episode status was draft, if so, we will not return it.
		return nil, errors.New("episode not accessable")
	}
	return dbEpisode.ToGQLEpisode(), nil
}

// UserList is the resolver for the userList field.
func (r *queryResolver) UserList(ctx context.Context, pagination model.Pagination) (*model.UserListResult, error) {
	var count int64
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbJWTUser models.DbUser
	if err := db.DB.Find(&dbJWTUser, models.DbUser{UserName: userName}).Count(&count).Error; err != nil {
		return nil, errors.New(err.Error())
	}
	if !dbJWTUser.IsAdmin {
		return nil, errors.New("user not to access this data")
	}

	var users []models.DbUser
	if err := db.DB.Model(&models.DbUser{}).Count(&count).Find(&users).Error; err != nil {
		return nil, errors.New(err.Error())
	}

	var rtUsers []*model.User
	for _, u := range users {
		rtUsers = append(rtUsers, u.ToGQLUser())
	}

	pageInfo := helpers.GetPageInfo(pagination.PageIndex, pagination.PerPage, int(count))
	return &model.UserListResult{
		TotalCount: int(count),
		Items:      rtUsers,
		PageInfo:   &pageInfo,
	}, nil
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, credential model.Credential) (*model.LoginData, error) {
	var user models.DbUser
	if err := db.DB.Model(models.DbUser{UserName: credential.UserName}).First(&user).Error; err != nil {
		return nil, errors.New("user with provided credentials not found")
	}
	if helpers.CheckPasswordHash(credential.Password, user.Password) {
		token, _ := helpers.GenerateJwt(user.UserName)
		return &model.LoginData{
			Token: token,
		}, nil
	}
	return nil, errors.New("user with provided credentials not found")
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	var dbJWTUser models.DbUser
	if err := db.DB.Model(&models.DbUser{UserName: userName}).Find(&dbJWTUser).Error; err != nil {
		return nil, errors.New(err.Error())
	}

	return dbJWTUser.ToGQLUser(), nil
}

// SiteConfig is the resolver for the siteConfig field.
func (r *queryResolver) SiteConfig(ctx context.Context) (*model.SiteConfig, error) {
	var siteConfig models.SiteConfig
	userName := helpers.JWTFromContext(ctx)
	if err := db.DB.First(&siteConfig).Error; err != nil {
		siteConfig = models.SiteConfig{
			ID:              uuid.New(),
			SiteName:        "CrispyPod",
			SiteDescription: "Super awesome podcast!",
			SiteUrl:         "https://crispypod.com",
			SetupComplete:   false,
		}
		db.DB.Create(&siteConfig)
	}

	return siteConfig.ToGQLSiteConfig(len(userName) != 0), nil
}

// DashboardInfo is the resolver for the dashboardInfo field.
func (r *queryResolver) DashboardInfo(ctx context.Context) (*model.DashboardInfo, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}

	// panic(fmt.Errorf("not implemented: DashboardInfo - dashboardInfo"))
	var rtn = &model.DashboardInfo{}
	var count int64
	db.DB.Model(models.Episode{}).Count(&count)
	rtn.EpisodeCount = int(count)
	return rtn, nil
}

// HookList is the resolver for the hookList field.
func (r *queryResolver) HookList(ctx context.Context, pagination model.Pagination) (*model.HookListResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: HookList - hookList"))
}

// Hook is the resolver for the hook field.
func (r *queryResolver) Hook(ctx context.Context, id string) (*model.Hook, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: Hook - hook"))
}

// HookLogList is the resolver for the hookLogList field.
func (r *queryResolver) HookLogList(ctx context.Context, pagination model.Pagination, hookID string) (*model.HookLogListResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: HookLogList - hookLogList"))
}

// DeployLogList is the resolver for the deployLogList field.
func (r *queryResolver) DeployLogList(ctx context.Context, pagination model.Pagination) (*model.DeployLogListResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: DeployLogList - deployLogList"))
}

// DeployLog is the resolver for the deployLog field.
func (r *queryResolver) DeployLog(ctx context.Context, id string) (*model.DeployLog, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: DeployLog - deployLog"))
}

// TriggerHook is the resolver for the triggerHook field.
func (r *queryResolver) TriggerHook(ctx context.Context, id string) (*model.BooleanResult, error) {
	userName := helpers.JWTFromContext(ctx)
	if len(userName) == 0 {
		return nil, errors.New("authorization failed")
	}
	panic(fmt.Errorf("not implemented: TriggerHook - triggerHook"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
