// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Credential struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type DashboardInfo struct {
	EpisodeCount int `json:"episodeCount"`
}

type DeletionResult struct {
	Result bool `json:"result"`
}

type Episode struct {
	ID                  string  `json:"id"`
	Title               string  `json:"title"`
	CreateTime          int     `json:"createTime"`
	Description         string  `json:"description"`
	EpisodeStatus       *int    `json:"episodeStatus,omitempty"`
	PublishTime         *int    `json:"publishTime,omitempty"`
	ThumbnailFileName   *string `json:"thumbnailFileName,omitempty"`
	ThumbnailUploadName *string `json:"thumbnailUploadName,omitempty"`
	AudioFileName       *string `json:"audioFileName,omitempty"`
	AudioFileUploadName *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration   *int    `json:"audioFileDuration,omitempty"`
	User                *User   `json:"user"`
}

type EpisodesResult struct {
	Items      []*Episode `json:"items"`
	TotalCount int        `json:"totalCount"`
	PageInfo   *PageInfo  `json:"pageInfo,omitempty"`
}

type LoginData struct {
	Token string `json:"token"`
}

type ModifyEpisodeInput struct {
	Title                   *string `json:"title,omitempty"`
	Description             *string `json:"description,omitempty"`
	EpisodeStatus           *int    `json:"episodeStatus,omitempty"`
	AudioFileName           *string `json:"audioFileName,omitempty"`
	AudioFileUploadName     *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration       *int    `json:"audioFileDuration,omitempty"`
	ThumbnailFileName       *string `json:"thumbnailFileName,omitempty"`
	ThumbnailFileUploadName *string `json:"thumbnailFileUploadName,omitempty"`
}

type NewEpisode struct {
	Title                   string  `json:"title"`
	Description             string  `json:"description"`
	EpisodeStatus           *int    `json:"episodeStatus,omitempty"`
	AudioFileName           *string `json:"audioFileName,omitempty"`
	AudioFileUploadName     *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration       *int    `json:"audioFileDuration,omitempty"`
	ThumbnailFileName       *string `json:"thumbnailFileName,omitempty"`
	ThumbnailFileUploadName *string `json:"thumbnailFileUploadName,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type Pagination struct {
	PageIndex int `json:"pageIndex"`
	PerPage   int `json:"perPage"`
}

type SiteConfig struct {
	ID              string `json:"id"`
	SiteName        string `json:"siteName"`
	SiteDescription string `json:"siteDescription"`
	SiteURL         string `json:"siteUrl"`
}

type SiteConfigInput struct {
	SiteName        string `json:"siteName"`
	SiteDescription string `json:"siteDescription"`
	SiteURL         string `json:"siteUrl"`
}

type User struct {
	ID          string `json:"id"`
	CreateTime  int    `json:"createTime"`
	Email       string `json:"email"`
	UserName    string `json:"userName"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
}

type UserInput struct {
	Email       string  `json:"email"`
	UserName    string  `json:"userName"`
	DisplayName string  `json:"displayName"`
	Password    *string `json:"password,omitempty"`
}

type UsersResult struct {
	Items      []*User   `json:"items"`
	TotalCount int       `json:"totalCount"`
	PageInfo   *PageInfo `json:"pageInfo,omitempty"`
}
