// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BooleanResult struct {
	Result bool `json:"result"`
}

type Credential struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type DashboardInfo struct {
	EpisodeCount int `json:"episodeCount"`
}

type DeployLog struct {
	ID         string `json:"id"`
	Log        string `json:"log"`
	Status     int    `json:"status"`
	CreateTime int    `json:"createTime"`
	Duration   int    `json:"duration"`
}

type DeployLogListResult struct {
	Items      []*DeployLog `json:"items"`
	TotalCount int          `json:"totalCount"`
	PageInfo   *PageInfo    `json:"pageInfo,omitempty"`
}

type Episode struct {
	ID                  string  `json:"id"`
	Title               string  `json:"title"`
	CreateTime          int     `json:"createTime"`
	Description         string  `json:"description"`
	EpisodeStatus       *int    `json:"episodeStatus,omitempty"`
	PublishTime         *int    `json:"publishTime,omitempty"`
	ThumbnailFileName   *string `json:"thumbnailFileName,omitempty"`
	ThumbnailUploadName *string `json:"thumbnailUploadName,omitempty"`
	AudioFileName       *string `json:"audioFileName,omitempty"`
	AudioFileUploadName *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration   *int    `json:"audioFileDuration,omitempty"`
	User                *User   `json:"user"`
}

type EpisodeListResult struct {
	Items      []*Episode `json:"items"`
	TotalCount int        `json:"totalCount"`
	PageInfo   *PageInfo  `json:"pageInfo,omitempty"`
}

type Hook struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Trigger    int    `json:"trigger"`
	WebURL     string `json:"webURL"`
	Method     string `json:"method"`
	Headers    string `json:"headers"`
	AppendBody string `json:"appendBody"`
}

type HookInput struct {
	Name       string  `json:"name"`
	Trigger    int     `json:"trigger"`
	WebURL     string  `json:"webURL"`
	Method     string  `json:"method"`
	Headers    *string `json:"headers,omitempty"`
	AppendBody *string `json:"appendBody,omitempty"`
}

type HookListResult struct {
	Items      []*Hook   `json:"items"`
	TotalCount int       `json:"totalCount"`
	PageInfo   *PageInfo `json:"pageInfo,omitempty"`
}

type HookLog struct {
	ID             string `json:"id"`
	HookID         string `json:"hookID"`
	Hook           *Hook  `json:"hook"`
	Status         int    `json:"status"`
	ResponseHeader string `json:"responseHeader"`
	ResponseBody   string `json:"responseBody"`
	CreateTime     int    `json:"createTime"`
	Duration       int    `json:"duration"`
}

type HookLogListResult struct {
	Items      []*HookLog `json:"items"`
	TotalCount int        `json:"totalCount"`
	PageInfo   *PageInfo  `json:"pageInfo,omitempty"`
}

type LoginData struct {
	Token string `json:"token"`
}

type ModifyEpisodeInput struct {
	Title                   *string `json:"title,omitempty"`
	Description             *string `json:"description,omitempty"`
	EpisodeStatus           *int    `json:"episodeStatus,omitempty"`
	AudioFileName           *string `json:"audioFileName,omitempty"`
	AudioFileUploadName     *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration       *int    `json:"audioFileDuration,omitempty"`
	ThumbnailFileName       *string `json:"thumbnailFileName,omitempty"`
	ThumbnailFileUploadName *string `json:"thumbnailFileUploadName,omitempty"`
}

type NewEpisode struct {
	Title                   string  `json:"title"`
	Description             string  `json:"description"`
	EpisodeStatus           *int    `json:"episodeStatus,omitempty"`
	AudioFileName           *string `json:"audioFileName,omitempty"`
	AudioFileUploadName     *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration       *int    `json:"audioFileDuration,omitempty"`
	ThumbnailFileName       *string `json:"thumbnailFileName,omitempty"`
	ThumbnailFileUploadName *string `json:"thumbnailFileUploadName,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type Pagination struct {
	PageIndex int `json:"pageIndex"`
	PerPage   int `json:"perPage"`
}

type SiteConfig struct {
	ID              string `json:"id"`
	SiteName        string `json:"siteName"`
	SiteDescription string `json:"siteDescription"`
	SiteURL         string `json:"siteUrl"`
	SetupComplete   bool   `json:"setupComplete"`
}

type SiteConfigInput struct {
	SiteName        *string `json:"siteName,omitempty"`
	SiteDescription *string `json:"siteDescription,omitempty"`
	SiteURL         *string `json:"siteUrl,omitempty"`
	SetupComplete   *bool   `json:"setupComplete,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	CreateTime  int    `json:"createTime"`
	Email       string `json:"email"`
	UserName    string `json:"userName"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
}

type UserInput struct {
	Email       string  `json:"email"`
	UserName    string  `json:"userName"`
	DisplayName string  `json:"displayName"`
	Password    *string `json:"password,omitempty"`
}

type UserListResult struct {
	Items      []*User   `json:"items"`
	TotalCount int       `json:"totalCount"`
	PageInfo   *PageInfo `json:"pageInfo,omitempty"`
}
